target_sources(${PROJECT_NAME} PRIVATE
  include/levk/core/array_map.hpp
  include/levk/core/bitmap.hpp
  include/levk/core/codepoint.hpp
  include/levk/core/colour.hpp
  include/levk/core/erased_ptr.hpp
  include/levk/core/hash.hpp
  include/levk/core/io.hpp
  include/levk/core/log_channel.hpp
  include/levk/core/log.hpp
  include/levk/core/maths.hpp
  include/levk/core/not_null.hpp
  include/levk/core/nvec.hpp
  include/levk/core/os.hpp
  include/levk/core/ref.hpp
  include/levk/core/services.hpp
  include/levk/core/singleton.hpp
  include/levk/core/span.hpp
  include/levk/core/std_types.hpp
  include/levk/core/time.hpp
  include/levk/core/transform.hpp
  include/levk/core/ubyte.hpp
  include/levk/core/version.hpp

  include/levk/core/io/converters.hpp
  include/levk/core/io/file_monitor.hpp
  include/levk/core/io/fs_media.hpp
  include/levk/core/io/media.hpp
  include/levk/core/io/path.hpp
  include/levk/core/io/zip_media.hpp

  include/levk/core/utils/data_store.hpp
  include/levk/core/utils/debug.hpp
  include/levk/core/utils/dirty_flag.hpp
  include/levk/core/utils/error.hpp
  include/levk/core/utils/execute.hpp
  include/levk/core/utils/expect.hpp
  include/levk/core/utils/profiler.hpp
  include/levk/core/utils/ratio.hpp
  include/levk/core/utils/shell.hpp
  include/levk/core/utils/src_info.hpp
  include/levk/core/utils/std_hash.hpp
  include/levk/core/utils/string.hpp
  include/levk/core/utils/sys_info.hpp
  include/levk/core/utils/tween.hpp
  include/levk/core/utils/type_guid.hpp
  include/levk/core/utils/unique.hpp
  include/levk/core/utils/vbase.hpp
)
