target_sources(${PROJECT_NAME} PRIVATE
  include/graphics/basis.hpp
  include/graphics/bitmap_font.hpp
  include/graphics/command_buffer.hpp
  include/graphics/common.hpp
  include/graphics/draw_view.hpp
  include/graphics/geometry.hpp
  include/graphics/glyph_pen.hpp
  include/graphics/glyph.hpp
  include/graphics/memory.hpp
  include/graphics/mesh_primitive.hpp
  include/graphics/qflags.hpp
  include/graphics/screen_rect.hpp
  include/graphics/texture.hpp
  include/graphics/context/defer_queue.hpp
  include/graphics/context/device.hpp
  include/graphics/context/physical_device.hpp
  include/graphics/context/queue_multiplex.hpp
  include/graphics/context/transfer.hpp
  include/graphics/context/vram.hpp
  include/graphics/render/buffering.hpp
  include/graphics/render/camera.hpp
  include/graphics/render/context.hpp
  include/graphics/render/descriptor_set.hpp
  include/graphics/render/pipeline_factory.hpp
  include/graphics/render/pipeline_flags.hpp
  include/graphics/render/pipeline_spec.hpp
  include/graphics/render/pipeline.hpp
  include/graphics/render/renderer.hpp
  include/graphics/render/rgba.hpp
  include/graphics/render/shader_buffer.hpp
  include/graphics/render/surface.hpp
  include/graphics/render/target.hpp
  include/graphics/render/vertex_input.hpp
  include/graphics/utils/command_rotator.hpp
  include/graphics/utils/deferred.hpp
  include/graphics/utils/layout_state.hpp
  include/graphics/utils/ring_buffer.hpp
  include/graphics/utils/utils.hpp
)
